<?php
/**
 * Static brand product & colour data mirrored from the Arise Paris React source of truth.
 *
 * @package Arise_Paris
 */

defined( 'ABSPATH' ) || exit;

function arise_paris_products_seed_data() {
	return array(
		array(
			'name'             => 'Active Man',
			'slug'             => 'active-man',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A confident everyday body spray presented with a bold blue identity for an energetic and modern fragrance experience.',
			'accent'           => '#1E4C8A',
			'accent_soft'      => '#EAF0F8',
			'gradient'         => 'linear-gradient(160deg, #0F2542 0%, #1E4C8A 100%)',
			'collection'       => 'bold-dynamic',
			'visual_identity'  => 'Deep blue, black — energetic and confident',
			'seo_title'        => 'Active Man Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Active Man 250 ml deodorant body spray by Arise Paris — a confident blue identity available for wholesale and distribution enquiries.',
			'image_alt'        => 'Arise Paris Active Man 250 ml deodorant body spray',
			'image'            => 'products/active-man.png',
		),
		array(
			'name'             => 'Addiction',
			'slug'             => 'addiction',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A bold body spray with a dark and expressive identity, created for those who prefer a strong and distinctive presence.',
			'accent'           => '#7A1E1E',
			'accent_soft'      => '#F3E7E7',
			'gradient'         => 'linear-gradient(160deg, #1A0808 0%, #7A1E1E 100%)',
			'collection'       => 'deep-rich',
			'visual_identity'  => 'Black, deep red — bold and intense',
			'seo_title'        => 'Addiction Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Addiction 250 ml deodorant body spray by Arise Paris — a bold, expressive variant for B2B fragrance distribution.',
			'image_alt'        => 'Arise Paris Addiction 250 ml deodorant body spray',
			'image'            => 'products/addiction.png',
		),
		array(
			'name'             => 'Barcelona',
			'slug'             => 'barcelona',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A vibrant city-inspired body spray with an energetic visual character and a warm, expressive personality.',
			'accent'           => '#C55A1E',
			'accent_soft'      => '#FAEDDF',
			'gradient'         => 'linear-gradient(160deg, #7A2E10 0%, #E39A28 100%)',
			'collection'       => 'bold-dynamic',
			'visual_identity'  => 'Yellow, orange, red — warm and vibrant',
			'seo_title'        => 'Barcelona Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Barcelona 250 ml deodorant body spray by Arise Paris — a warm, vibrant variant available for wholesale enquiries.',
			'image_alt'        => 'Arise Paris Barcelona 250 ml deodorant body spray',
			'image'            => 'products/barcelona.png',
		),
		array(
			'name'             => 'Black Musk',
			'slug'             => 'black-musk',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A deep musk-inspired body spray with a dark, sophisticated appearance and a rich, confident character.',
			'accent'           => '#5C3E7A',
			'accent_soft'      => '#EEE9F3',
			'gradient'         => 'linear-gradient(160deg, #0A0A0A 0%, #5C3E7A 100%)',
			'collection'       => 'deep-rich',
			'visual_identity'  => 'Black, charcoal, purple — mysterious',
			'seo_title'        => 'Black Musk Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Black Musk 250 ml deodorant body spray by Arise Paris — a sophisticated musk-inspired variant for distributors.',
			'image_alt'        => 'Arise Paris Black Musk 250 ml deodorant body spray',
			'image'            => 'products/black-musk.png',
		),
		array(
			'name'             => 'Crush',
			'slug'             => 'crush',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A soft and expressive body spray with a graceful visual style, designed for a fresh and memorable everyday presence.',
			'accent'           => '#A0367A',
			'accent_soft'      => '#F5E8F0',
			'gradient'         => 'linear-gradient(160deg, #E7D9E8 0%, #A0367A 100%)',
			'collection'       => 'soft-expressive',
			'visual_identity'  => 'Ivory, purple, pink — expressive',
			'seo_title'        => 'Crush Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Crush 250 ml deodorant body spray by Arise Paris — a graceful and expressive variant for B2B partners.',
			'image_alt'        => 'Arise Paris Crush 250 ml deodorant body spray',
			'image'            => 'products/crush.png',
		),
		array(
			'name'             => 'Forest Spice',
			'slug'             => 'forest-spice',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A green and nature-inspired body spray combining a fresh visual identity with a warm, spicy character.',
			'accent'           => '#4F7A3B',
			'accent_soft'      => '#EAF1E4',
			'gradient'         => 'linear-gradient(160deg, #B7CFA1 0%, #4F7A3B 100%)',
			'collection'       => 'soft-expressive',
			'visual_identity'  => 'Green, botanical — fresh and nature-inspired',
			'seo_title'        => 'Forest Spice Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Forest Spice 250 ml deodorant body spray by Arise Paris — a fresh, nature-inspired variant for retail partners.',
			'image_alt'        => 'Arise Paris Forest Spice 250 ml deodorant body spray',
			'image'            => 'products/forest-spice.png',
		),
		array(
			'name'             => 'Goodness Oud',
			'slug'             => 'goodness-oud',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A rich oud-inspired body spray presented in warm amber and brown tones for a deep and refined fragrance experience.',
			'accent'           => '#8A5A1E',
			'accent_soft'      => '#F3E9D9',
			'gradient'         => 'linear-gradient(160deg, #2A1608 0%, #B99A5B 100%)',
			'collection'       => 'deep-rich',
			'visual_identity'  => 'Brown, amber, gold — rich',
			'seo_title'        => 'Goodness Oud Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Goodness Oud 250 ml deodorant body spray by Arise Paris — a refined oud-inspired variant for wholesale and export.',
			'image_alt'        => 'Arise Paris Goodness Oud 250 ml deodorant body spray',
			'image'            => 'products/goodness-oud.png',
		),
		array(
			'name'             => 'Romantic',
			'slug'             => 'romantic',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A warm and elegant body spray with a romantic visual identity, created for graceful and expressive everyday wear.',
			'accent'           => '#B93A3A',
			'accent_soft'      => '#F7E7E7',
			'gradient'         => 'linear-gradient(160deg, #F5EBD8 0%, #B93A3A 100%)',
			'collection'       => 'soft-expressive',
			'visual_identity'  => 'Ivory, red — warm and elegant',
			'seo_title'        => 'Romantic Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Romantic 250 ml deodorant body spray by Arise Paris — a warm, elegant variant for retail distribution.',
			'image_alt'        => 'Arise Paris Romantic 250 ml deodorant body spray',
			'image'            => 'products/romantic.png',
		),
		array(
			'name'             => 'Signature',
			'slug'             => 'signature',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A clean and refined body spray with a polished signature identity, suitable for a versatile and confident presence.',
			'accent'           => '#5F7A94',
			'accent_soft'      => '#EAEEF3',
			'gradient'         => 'linear-gradient(160deg, #B9BDC5 0%, #5F7A94 100%)',
			'collection'       => 'bold-dynamic',
			'visual_identity'  => 'Silver, light blue — clean and refined',
			'seo_title'        => 'Signature Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Signature 250 ml deodorant body spray by Arise Paris — a clean, refined variant for B2B partners.',
			'image_alt'        => 'Arise Paris Signature 250 ml deodorant body spray',
			'image'            => 'products/signature.png',
		),
		array(
			'name'             => 'Sweet Love',
			'slug'             => 'sweet-love',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A soft body spray with a delicate pink identity, created to express warmth, charm and everyday elegance.',
			'accent'           => '#D48AA8',
			'accent_soft'      => '#FBEEF3',
			'gradient'         => 'linear-gradient(160deg, #FCE4EC 0%, #D48AA8 100%)',
			'collection'       => 'soft-expressive',
			'visual_identity'  => 'White, soft pink — delicate and sweet',
			'seo_title'        => 'Sweet Love Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Sweet Love 250 ml deodorant body spray by Arise Paris — a delicate, expressive variant for retail markets.',
			'image_alt'        => 'Arise Paris Sweet Love 250 ml deodorant body spray',
			'image'            => 'products/sweet-love.png',
		),
		array(
			'name'             => 'Temptation',
			'slug'             => 'temptation',
			'product_type'     => 'Deodorant Body Spray',
			'net_volume'       => '250 ml',
			'fluid_ounce'      => '8.45 fl. oz.',
			'short_description'=> 'A captivating body spray with a deep and dramatic visual identity for a bold and memorable fragrance experience.',
			'accent'           => '#7A1E4A',
			'accent_soft'      => '#F1E1EA',
			'gradient'         => 'linear-gradient(160deg, #1A0812 0%, #B0246E 100%)',
			'collection'       => 'deep-rich',
			'visual_identity'  => 'Black, burgundy, magenta — dramatic',
			'seo_title'        => 'Temptation Deodorant Body Spray | Arise Paris',
			'meta_description' => 'Temptation 250 ml deodorant body spray by Arise Paris — a bold, dramatic variant for distribution partners.',
			'image_alt'        => 'Arise Paris Temptation 250 ml deodorant body spray',
			'image'            => 'products/temptation.png',
		),
	);
}

function arise_paris_journey_colours() {
	return array(
		'active-man' => array(
			'glow' => '#1069D8',
			'mid'  => '#0A2451',
			'deep' => '#081224',
		),
		'addiction' => array(
			'glow' => '#A62520',
			'mid'  => '#3D090B',
			'deep' => '#09090B',
		),
		'barcelona' => array(
			'glow' => '#EF8A19',
			'mid'  => '#D44318',
			'deep' => '#3A1604',
		),
		'black-musk' => array(
			'glow' => '#6A3C82',
			'mid'  => '#211226',
			'deep' => '#08090C',
		),
		'crush' => array(
			'glow' => '#C02E7B',
			'mid'  => '#8B3CA5',
			'deep' => '#1A0A20',
		),
		'forest-spice' => array(
			'glow' => '#68A84A',
			'mid'  => '#274D2D',
			'deep' => '#08130C',
		),
		'goodness-oud' => array(
			'glow' => '#B87621',
			'mid'  => '#5A3012',
			'deep' => '#170B04',
		),
		'romantic' => array(
			'glow' => '#E43D4E',
			'mid'  => '#8F1C32',
			'deep' => '#1B060C',
		),
		'signature' => array(
			'glow' => '#4E83C5',
			'mid'  => '#2B4A70',
			'deep' => '#0A1424',
		),
		'sweet-love' => array(
			'glow' => '#E85A9F',
			'mid'  => '#8E3462',
			'deep' => '#1D0A14',
		),
		'temptation' => array(
			'glow' => '#B21962',
			'mid'  => '#54122D',
			'deep' => '#190A14',
		),
	);
}

function arise_paris_collections() {
	return array(
		'bold-dynamic'    => array(
			'title'       => __( 'Bold & Dynamic', 'arise-paris' ),
			'description' => __( 'Confident visual identities created for energetic and expressive everyday positioning.', 'arise-paris' ),
		),
		'deep-rich'       => array(
			'title'       => __( 'Deep & Rich', 'arise-paris' ),
			'description' => __( 'Darker, richer and more dramatic body spray personalities with a premium presence.', 'arise-paris' ),
		),
		'soft-expressive' => array(
			'title'       => __( 'Soft & Expressive', 'arise-paris' ),
			'description' => __( 'Fresh, graceful and expressive variants designed for diverse fragrance preferences.', 'arise-paris' ),
		),
	);
}
